### PR TITLE
Use dplyr for subsetting and analysis

### PR DESCRIPTION
**Pull request by karawoo**
At the recent WSU workshop I taught subsetting, data manipulation, and split-apply-combine-style data analysis using dplyr rather than base (we did cover bracket subsetting first). It went really well and @tracykteal and I talked about incorporating this material into the lessons. This pull request adds the dplyr lesson and removes `04-manipulating-data` and `05-analyzing-data`. The first few paragraphs of `04-manipulating-data` that deal with extracting columns from data frames by name is moved to `03-data-frames`.

I generated updated HTML pages. It looks like currently the HTML and .Rmd files are not in sync, so some of the changes to the HTML files in this pull request are the result of previously merged changes to the .Rmd files.

In this workshop we used a joined version of the Portal data set that includes the info from `species.csv`, `surveys.csv`, and `plots.csv`. This file was the output of the previous day's OpenRefine and SQL lessons. I've included that data here so that the HTML files can be built from the .Rmd, but Tracy and I also talked about adding this data to Figshare at some point. The data has been cleaned up a little to remove the values in the `sex` column that are things like "R", "P", and "Z" and replace them with empty strings (which seems to be how missing data in this column is otherwise represented).

### CODE REVIEW

**Comment by karthik** [comment]
> a 2 letter code, see the species.csv file for correspondance

s/correspondance/correspondence

> record_id , month, day, year, plot_id, species_id (a 2 letter code, see the species.csv file for correspondance), sex ("M" for males and "F" for females), hindfood_length (the length of the hindfoot in millimeters),weight (the weight in grams), genus, species, taxa, and plot_type.

This whole section could be a markdown table to make it much easier to read, especially when an instructor is quickly working through the material.

```
surveys <- read.csv('portal_data_joined.csv')
```

This will need `stringsAsFactors = FALSE` or we should use `readr`'s `read_csv` that automatically takes care of all these annoyances. I mean, teaching `dplyr` is already black boxy (not getting into the underlying machinery) so no reason we can't do more of this.

> If we want to check that our data has been loaded, we can print the variable's value: surveys

Or wrap any such assignment in parentheses. E.g. to make the assignment and print to screen:

`(surveys <- read.csv('portal_data_joined.csv'))`


> Let's now check the __str__ucture of this data.frame in more details with the function str():

If you're going all out `dplyr`, `glimpse` provider a simpler `str`.

e.g. 

```r
> glimpse(iris)
Observations: 150
Variables:
$ Sepal.Length (dbl) 5.1, 4.9, 4.7, 4.6, 5.0, 5.4, 4.6, 5.0, 4.4, 4.9, 5.4, 4.8, 4.8,...
$ Sepal.Width  (dbl) 3.5, 3.0, 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3.0,...
$ Petal.Length (dbl) 1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4,...
$ Petal.Width  (dbl) 0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1,...
$ Species      (fctr) setosa, setosa, setosa, setosa, setosa, setosa, setosa, setosa,...
Arrrr> str(iris)
'data.frame':	150 obs. of  5 variables:
 $ Sepal.Length: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
 $ Sepal.Width : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
 $ Petal.Length: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
 $ Petal.Width : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
 $ Species     : Factor w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...
```

**Comment by karthik** [comment]
Also, the readme links to the raw html files in the index. It would make more sense to link directly to the rendered versions of files.

This part here: 

image

**Comment by karawoo** [comment]
Thanks @karthik for the thorough comments. I'll modify the text in the places you suggest later today.

I agree about the links in the readme. The makefile copies index.md to the readme, and it makes sense for index.md to link to the HTML pages. I can modify the makefile but I historically break everything I touch when it comes to make, so I'd appreciate suggestions.

The loading of the CSV and viewing the structure is something that happens well before I introduce dplyr. I'm afraid that introducing it earlier and loading the data with `read_csv()` will make people think that you have to use external packages to get data into R, but maybe I'm underestimating the learners. I've kept `stringsAsFactors` so I could briefly explain factors when we're looking at the output of `str()`; I'd be happy to use `stringsAsFactors = FALSE` but I haven't found a way to explain it that doesn't basically boil down to "just trust me" when they haven't learned what factors are in the first place.

**Comment by fmichonneau** [comment]
Thanks @karawoo for this great addition! Using dplyr really makes it easier for beginner to do these data manipulations.

I think teaching stringsAsFactors = FALSE is important. The second lesson covers factors. That being said, from what I remember, what we do in these lessons work without any annoyances with the default stringsAsFactors=TRUE.

I noticed that you read the data from the same folder as the script. In the 00 lesson, we talk about how it's good practice to put data in a different folder. Could you please update the PR so the data is in a different folder? 

Talking about data, the data set you use for this needs to be accessible. I think we agreed that no data should go in the repository. Could you please either put it in your own figshare repo or ask Ethan & Morgan to add it to theirs? Then we can update the setup.R script to fetch it with the rest of the data sets.

From a quick look, it seems that a lot of the code for this lesson ended up in the skeleton file. Was it your intention? I have used the skeleton file mostly to provide participants code that was long/error-prone.

Thanks again!

**Comment by ethanwhite** [comment]
I'm happy to add a "big table" version of the dataset to the Portal Teaching Database. @karawoo - can you give me the specifics of what the data file needs to be and I'll get it added (I'm going to add it to the script for rebuilding easily, so I don't just want to grab the version in the PR).

**Comment by karawoo** [comment]
Thanks @ethanwhite. This data set was the output of the previous day's OpenRefine and SQL lessons, of which I followed probably 60% as I was floating around to help people while @naupaka taught. I'm pretty sure this data set would be replicated by joining `surveys.csv` with `plots.csv` on `plot_id` and with `species.csv` on `species_id`. We also removed the values in the `sex` column that were things like "R", "P", and "Z" and replaced those with empty strings (which seems to be how missing data is otherwise represented in this column). Maybe @naupaka can chime in if there's anything important I'm missing here, but I think that's about it. 

Since this version of the data is going to go on Figshare I will just remove it from the repo entirely. Here's a git question for you all: since I'm the only one who has worked on this branch, is it safe for me to do a `filter-branch` and remove the csv entirely (and make the repo a little smaller)? Or should I just remove the data but let it remain in the history?

**Comment by karawoo** [comment]
@fmichonneau re: the skeleton lessons, I misunderstood and thought the point of those was to provide learners with all the code that they saw in the workshop (when I've taught people always ask for that). I can go ahead and remove the dplyr code from the skeleton lessons later today.

**Comment by tracykteal** [comment]
The data being in the repo is my fault. I asked that she just put it in here while we are evaluating the PR. Before committing to putting it in FigShare, we should be sure it's the data that we want to use, and having it here let's us run through the code. 

Can we leave it this way until the PR is accepted and then update FigShare with the dataset and make that change to the link to the dataset in a separate PR?

**Comment by tracykteal** [comment]
I don't think we have a clear policy on the skeleton-lesson file. I like the idea of having all the code for the lesson in one file. I wonder if it's hard to keep it synced with the lesson though. I tend to just copy long code blocks in to the ether pads. @fmichonneau

**Comment by naupaka** [comment]
So the flow of the first day of the WSU workshop was (to give context to @karawoo's dplyr lesson, which happened on day 2):

* Work through cleaning up in Excel the 1977 tab in the `xls` file from the [data-ecology repo](https://github.com/datacarpentry/data-ecology/tree/gh-pages/messy-data) in pairs, and have students self-document as they go.
*  Then give students tweaked versions of the three `csv` files: `plots.csv`, `species.csv`, and `surveys.csv` (canonical versions taken from [Figshare](http://figshare.com/articles/Portal_Project_Teaching_Database/1314459) and then modified by me). These were modified such that particular errors were introduced into each to specifically allow teaching of the major OpenRefine tools (text/numeric/scatterplot facets, text clustering, etc). I could post these modified files somewhere, put the diffs in a gist, email to @ethanwhite, or... 
* We then cleaned (as a group) each of these files in OpenRefine, with changes documented to json for each, and exported to `csv` after 'QC'. I could put the OpenRefine `json` files documenting these fixes somewhere, if that would be helpful.
* These three cleaned `csv` files get pulled into a SQLite database using the Firefox plugin, and we run through the SQL lessons. Then, at the end of the SQL lessons, do a double join to get a single large table that is then exported to `csv` for playing with in R.

**Comment by ethanwhite** [comment]
> I could post these modified files somewhere, put the diffs in a gist, email to @ethanwhite, or... 

Messy data for cleaning up is a common thing that pops up in Data Carpentry discussions. I suggest that we agree on a common set of messy issues to introduce and then post a single messy version of the dataset in the main Portal Teaching DB on figshare.

Additional discussion of this and recommendations for messiness to introduce should probably go in the existing https://github.com/datacarpentry/planning/issues/3.

**Comment by lwasser** [comment]
:+1:

**Comment by ethanwhite** [comment]
> Can we leave it this way until the PR is accepted and then update FigShare with the dataset and make that change to the link to the dataset in a separate PR? 

No strong objections. Only downsides are that the size of the repo will go up and understanding the history *might* be a little more confusing.

**Comment by ethanwhite** [comment]
> Since this version of the data is going to go on Figshare I will just remove it from the repo entirely. Here's a git question for you all: since I'm the only one who has worked on this branch, is it safe for me to do a filter-branch and remove the csv entirely (and make the repo a little smaller)? Or should I just remove the data but let it remain in the history?

I think it's fine to rewrite history in PR branches that aren't being used by anyone else (and in the vast majority of cases they aren't). This approach is used regularly in SWC. @hlapp suggested at some point that rewriting history to clean up a PR before it goes in should trigger a new branch and PR. We need an official policy on this detail, but generally it's certainly fine and in fact encouraged to cleanup the history on PRs before they are finally merged.

**Comment by tracykteal** [comment]
Good point. I guess I'm just not sure how to handle these PRs that involve dataset changes. I started an issue for general thoughts on that. https://github.com/datacarpentry/planning/issues/13

**Comment by karawoo** [comment]
On the issue of the skeleton lessons, the makefile generates them so it's not *too* hard to keep them in sync. Learners at WSU seemed to have a hard time following along using commands pasted in the Etherpad even though one of the helpers was typing all the commands in pretty promptly. I ended up creating a link (I can't remember if it was a hard link or a soft link that worked in the end) from the script I was editing to my public Dropbox and I shared that link with them. Then I just needed to remember to save frequently, and the Dropbox version would automatically update so they could see what I had just added.

If the lessons are not currently set up to add all the code to the skeleton lessons file then maybe I should undo this for now and make it part of a separate PR if we decide we want this.

**Comment by naupaka** [comment]
Soft links. We tried hard links first but apparently then Dropbox wouldn't pick up the changes when the original was saved.

**Comment by karawoo** [comment]
Ah yes, right, thanks.

**Comment by karawoo** [comment]
I've made some of the changes @karthik suggested for the description of the data, added `stringsAsFactors = FALSE`, and removed my dplyr code chunks from the skeleton lessons. However I think having `stringsAsFactors = FALSE` makes the discussion of factors, which comes immediately after loading the data, pretty illogical; we will have just told them they *don't* want factors, and then we spend a bunch of time talking about factors that they aren't going to use because their data doesn't have factors...

I didn't do anything about the data set yet as I don't think we reached a decision on the best way to move forward with that. If getting these materials into the repo isn't time-sensitive, then I'd be inclined to wait until the combined data set is on Figshare and then update this PR before it's merged, just so that we keep that large-ish file out.

**Comment by karthik** [comment]
> However I think having stringsAsFactors = FALSE makes the discussion of factors, which comes immediately after loading the data, pretty illogical;

Agreed. Good call. So it would make sense to leave it out and teach that when explaining factors.

**Comment by karawoo** [comment]
@fmichonneau is this ok with you?

**Comment by fmichonneau** [comment]
Hi @karawoo,

Sorry for the delay, lots of meetings today :disappointed: 

Yes, the lesson is great. Thanks again!

The last minor point for me is that the data set should be read from the `data/` folder instead of the same directory as the script.

I would also prefer to not have the dataset included in this PR before merging. My suggestion for now would be for you to put it up on figshare and downloading it from there (using the `setup.R` script), until we settle on how to get from the raw data to your version of the dataset to include in @ethanwhite's repository. If you prefer to put it somewhere else, that's fine too.

cheers!

**Comment by karawoo** [comment]
I feel a little weird posting the data to Figshare myself since I've had so little to do with the creation of this data set. But if this is the best way, I can do that. And yes, once the data issue is sorted out I will have it downloaded to a `data/` folder. 

@fmichonneau are you fine with the proposal to keep the default `stringsAsFactors`?

**Comment by fmichonneau** [comment]
The dataset is released under CC-BY (see http://figshare.com/articles/Portal_Project_Teaching_Database/1314459), so as long as you give credit where it's due, it's fine :)

Yes, no problem with stringsAsFactors.

  Thanks!

**Comment by ethanwhite** [comment]
> I feel a little weird posting the data to Figshare myself since I've had so little to do with the creation of this data set. But if this is the best way, I can do that.

> The dataset is released under CC-BY, so as long as you give credit where it's due, it's fine :)

It's true that it's fine from a licensing perspective, but it does strike me as a little weird to use figshare (an archiving service) for what amounts to a very temporary data file that's a near complete copy of another figshare repo. There are probably also some social issues here that while they aren't an issue in this case (because Morgan & I don't care) could be fairly serious in other similar cases. I would personally lean towards a more temporary link like a public Dropbox link that can just be deleted when we're done with it.

**Comment by karawoo** [comment]
I think Dropbox is the best temporary solution. I will make these changes probably tomorrow. Thanks for all the feedback!

**Comment by fmichonneau** [comment]
I agree @ethanwhite. I didn't consider the archival aspect of figshare. As the content can easily be deleted, I just viewed it as an easy way of publishing the data set and making it readily accessible if only temporarily.

**Comment by karawoo** [comment]
I've updated the lessons to download the data file from my public Dropbox. I had to use the `curl` package because `download.file()` doesn't support https (as far as I know). The lessons and `setup.R` script now download the data to, and read the data from, the `data/` folder. The default `stringsAsFactors` is restored, and I have removed the joined data file from the history of the branch (I *think*; this is my first attempt at removing a file from the whole history).

I think this addresses all the suggestions people had about this PR. The issue of the lesson links in the readme pointing to the raw html is still out there, but I think fixes to that should go in a separate PR.

**Comment by fmichonneau** [comment]
Thanks @karawoo, It looks great!

R supports natively https download (since 3.2.0) using `download.file(...., method="libcurl")` but we can change this later. And it's my understanding that in some cases it might not work on Windows.

**Pull request merged**
