### PR TITLE
Adding ggplot2

### PR DESCRIPTION
**Pull request by apawlik**
This is branched out from https://github.com/apawlik/R-ecology/commit/fb372d31d2f9d624bf0144179da16983d1c209a3 so once https://github.com/datacarpentry/R-ecology/pull/17 is merged this should merge nicely too.

I added ggplot2 lesson in HTML version and modified Makefile accordingly. I don't understand knitr (sorry!) so don't know if I need to commit also all images that are produced? Probably I do. But they are produced in /img with really poor naming pattern (all are "r-lesson-unnamed-chunk-xx-x.png"). I'm trying to understand how to label the chunks of code but not quite getting there yet. Also, the knitr option say results='hide' so don't know why the images are produced :-(

### CODE REVIEW

**Comment by fmichonneau** [comment]
Hi @apawlik !

Thanks for doing this. 

>  I need to commit also all images that are produced? Probably I do. But they are produced in /img with really poor naming pattern (all are "r-lesson-unnamed-chunk-xx-x.png"). I'm trying to understand how to label the chunks of code but not quite getting there yet.

The names of the image files produced by the chunks are determined by the names of the chunk. The name of a chunk needs to be placed after the letter `r` in the chunk definition:

    ```{r chunk-name, ...}
    some r code
    ```

If you don't have time to fix it now, I'm happy to do it once this PR is merged (but in this case it might be best to not commit the images named `....unnamed-chunk...`

> Also, the knitr option say results='hide' so don't know why the images are produced 

Results only control what is printed on the R console not the figures. You can learn more about the knitr options here: http://yihui.name/knitr/options/

**Comment by tracykteal** [comment]
Is the main point of this PR to add the HTML for the ggplot lesson? If so, maybe we can do this differently, since this PR seems to also redo the Makefile and touch all the existing lessons?

**Comment by tracykteal** [comment]
#17 is merged now though

**Comment by tracykteal** [comment]
@apawlik @fmichonneau Should this PR be standing, or have we resolved this issue in another PR?

**Comment by apawlik** [comment]
I'm with poor Internet till Sunday evening. Will check as soon as I get
properly online and resolve!

Training Leader
The Software Sustainability Institute
w: www.software.ac.uk
t: @aleksandrana | @SoftwareSaved

**Comment by apawlik** [comment]
@fmichonneau @tracykteal I think this has been resolved with another PR. Closing.

**Pull request closed without merging**
