### PR TITLE
Clean up of the repository

### PR DESCRIPTION
**Pull request by fmichonneau**
I slightly edited the CONTRIBUTING and CONTRIBUTOR files.

I also attempted to clean up some less visited corners of the repository. Here is a summary of the changes:

- I deleted the folder figures/ : I think it was left-over from older lessons that used a different prefix to build the lessons
- I deleted the distributed/ folder that contained some Rmd files and a zip files of the lessons (including the dataset). I think it was a left-over from the first data carpentry and doesn't seem to belong to the main repository for this lesson
- the folder materials had a mix of draft of the initial R data carpentry lessons (that I deleted), exact copies from older software carpentry lesson (that I deleted), some material that we typically don't have time to teach in the "normal" data carpentry curriculum (mostly developed by @emhart, that I renamed with the `supp-` prefix and placed at the root of the repository)
- I left the r-ggplot2 directory as is. I copied in it a PDF file that contains a different ggplot2 lesson developed by @karthik that was originally in the ref/ directory. I deleted the object.Rmd file that contained an introduction to data structures in R (that will not be covered in most data carpentry, and that has been improved in software carpentry).

Let me know if you think I was too generous with this re-organization or if there are good reasons to keep some of the files that I deleted.

### CODE REVIEW

**Comment by tracykteal** [comment]
Thanks @fmichonneau These are great and definitely needed. I'll go through them, and as @lwasser says, we should even have a chance to try them this week

**Comment by karawoo** [comment]
This looks like a lot of great stuff. Downloading the data from figshare will be especially helpful; it doesn't look like the data is currently included anywhere in the repo (`02-starting-with-data.Rmd` looks for it in `../../data/biology/surveys.csv`) so I can't knit the lessons locally as-is.

**Comment by fmichonneau** [comment]
Kara, I merged the PR that took care of building the lessons with the
figshare dataset. Let me know if you have any questions.

The rest of this PR takes care of cleaning up old files that I think you
should be removed.

**Comment by hlapp** [comment]
@fmichonneau can you confirm that this is still fully up-to-date? The diff is extensive, and difficult for me to judge whether it's all correct and intended. if you know it's all good perhaps you should just go ahead and merge it yourself.

**Comment by fmichonneau** [comment]
yes it is, as far as I know. I'm going to go ahead and merge. If it deletes files that are still needed for some reason, open an issue and I'll resurrect them.

**Pull request merged**
